"""Sales Analytics dashboard page for Milestone 2."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
import sys

import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src import config
from src.analytics import (
    apply_filters,
    calculate_sales_kpis,
    monthly_summary,
    quarter_summary,
    trend_phrase,
)
from src.data_pipeline import load_clean_export
from src.visualizations import (
    COLOR_BLUE,
    COLOR_REVENUE,
    COLOR_TEAL,
    apply_chart_theme,
    format_currency,
    format_metric,
    format_percent,
    load_css,
    render_chart,
    render_executive_insights,
    render_footer,
    render_insight,
    render_kpi_cards,
    render_page_header,
    render_sidebar,
)


def peak_month_insight(monthly_df, value_column: str, label: str) -> str:
    """Generate a dynamic peak-period insight."""
    if monthly_df.empty:
        return f"No {label.lower()} records are available for the selected filters."
    peak = monthly_df.loc[monthly_df[value_column].idxmax()]
    low = monthly_df.loc[monthly_df[value_column].idxmin()]
    return (
        f"{label} peaked in {peak['Month']} and was lowest in {low['Month']}, "
        "indicating the strongest and weakest periods in the selected view."
    )


def main() -> None:
    """Render the Sales Analytics page."""
    st.set_page_config(page_title="Sales Analytics | Rialto", layout="wide")
    load_css()

    df = load_clean_export()
    last_refresh = datetime.now()
    filters = render_sidebar(df, last_refresh)
    filtered_df = apply_filters(df, filters)

    render_page_header(
        "Descriptive Analytics",
        "Sales Analytics",
        "Revenue, transaction volume, growth, and distribution insights.",
    )

    if filtered_df.empty:
        st.warning("No records match the selected filters.")
        render_footer(last_refresh)
        st.stop()

    kpis = calculate_sales_kpis(filtered_df)
    cards = [
        {
            "icon": "$",
            "title": "Total Revenue",
            "value": format_currency(kpis["total_revenue"]),
            "description": "Revenue generated by the selected transactions.",
        },
        {
            "icon": "#",
            "title": "Total Transactions",
            "value": format_metric(kpis["total_transactions"]),
            "description": "Transaction count in the selected data.",
        },
        {
            "icon": "AOV",
            "title": "Average Order Value",
            "value": format_currency(kpis["average_order_value"]),
            "description": "Average revenue per transaction.",
        },
        {
            "icon": "MAX",
            "title": "Highest Transaction",
            "value": format_currency(kpis["highest_transaction"]),
            "description": "Largest transaction value in the selection.",
        },
        {
            "icon": "MIN",
            "title": "Lowest Transaction",
            "value": format_currency(kpis["lowest_transaction"]),
            "description": "Smallest transaction value in the selection.",
        },
        {
            "icon": "MG",
            "title": "Monthly Growth",
            "value": format_percent(kpis["monthly_growth_pct"]),
            "description": "Latest month revenue vs previous month.",
        },
        {
            "icon": "RG",
            "title": "Revenue Growth",
            "value": format_percent(kpis["revenue_growth_pct"]),
            "description": "Latest month revenue vs first selected month.",
        },
    ]
    render_kpi_cards(cards)

    monthly = monthly_summary(filtered_df)
    quarterly = quarter_summary(filtered_df)

    fig = go.Figure()
    fig.add_trace(
        go.Scatter(
            x=monthly["Month"],
            y=monthly["monthly_revenue"],
            mode="lines+markers",
            line=dict(color=COLOR_REVENUE, width=3),
            marker=dict(size=8),
            hovertemplate="<b>%{x}</b><br>Revenue: $%{y:,.2f}<extra></extra>",
        )
    )
    fig.update_yaxes(tickprefix="$", separatethousands=True)
    render_chart(apply_chart_theme(fig, "Monthly Revenue Trend"))
    render_insight(peak_month_insight(monthly, "monthly_revenue", "Revenue"))

    fig = px.bar(
        quarterly,
        x="Quarter",
        y="quarterly_revenue",
        color_discrete_sequence=[COLOR_REVENUE],
    )
    fig.update_traces(hovertemplate="<b>%{x}</b><br>Revenue: $%{y:,.2f}<extra></extra>")
    fig.update_yaxes(tickprefix="$", separatethousands=True)
    render_chart(apply_chart_theme(fig, "Quarterly Revenue"))
    render_insight(peak_month_insight(quarterly.rename(columns={"Quarter": "Month", "quarterly_revenue": "monthly_revenue"}), "monthly_revenue", "Quarterly revenue"))

    fig = px.bar(
        monthly,
        x="Month",
        y="monthly_transactions",
        color_discrete_sequence=[COLOR_BLUE],
    )
    fig.update_traces(hovertemplate="<b>%{x}</b><br>Transactions: %{y:,}<extra></extra>")
    fig.update_yaxes(separatethousands=True)
    render_chart(apply_chart_theme(fig, "Monthly Transactions"))
    render_insight(peak_month_insight(monthly, "monthly_transactions", "Transaction volume"))

    fig = px.histogram(
        filtered_df,
        x=config.REVENUE_COLUMN,
        nbins=25,
        color_discrete_sequence=[COLOR_TEAL],
    )
    fig.update_traces(hovertemplate="Revenue range: %{x}<br>Transactions: %{y:,}<extra></extra>")
    fig.update_xaxes(tickprefix="$", separatethousands=True)
    render_chart(apply_chart_theme(fig, "Revenue Distribution"))
    render_insight(
        f"The median transaction is {format_currency(filtered_df[config.REVENUE_COLUMN].median())}, "
        "showing the central spending level within the selected revenue distribution."
    )

    grouped = (
        filtered_df.groupby(["Month", "Quarter"], as_index=False)[config.REVENUE_COLUMN]
        .sum()
        .rename(columns={config.REVENUE_COLUMN: "revenue"})
    )
    fig = px.bar(grouped, x="Month", y="revenue", color="Quarter", barmode="group")
    fig.update_traces(hovertemplate="<b>%{x}</b><br>Revenue: $%{y:,.2f}<extra></extra>")
    fig.update_yaxes(tickprefix="$", separatethousands=True)
    render_chart(apply_chart_theme(fig, "Revenue by Month and Quarter"))
    render_insight("The grouped view compares monthly revenue while preserving quarter context for seasonal review.")

    fig = px.box(filtered_df, y=config.REVENUE_COLUMN, color="Revenue_Band")
    fig.update_traces(hovertemplate="Revenue: $%{y:,.2f}<extra></extra>")
    fig.update_yaxes(tickprefix="$", separatethousands=True)
    render_chart(apply_chart_theme(fig, "Revenue Box Plot"))
    render_insight(
        f"The highest transaction is {format_currency(kpis['highest_transaction'])}, "
        "which helps identify the upper range of transaction values."
    )

    fig = go.Figure()
    fig.add_trace(
        go.Scatter(
            x=monthly["Month"],
            y=monthly["cumulative_revenue"],
            mode="lines+markers",
            fill="tozeroy",
            line=dict(color=COLOR_REVENUE, width=3),
            hovertemplate="<b>%{x}</b><br>Cumulative revenue: $%{y:,.2f}<extra></extra>",
        )
    )
    fig.update_yaxes(tickprefix="$", separatethousands=True)
    render_chart(apply_chart_theme(fig, "Cumulative Revenue Trend"))
    render_insight(
        f"Cumulative revenue reached {format_currency(monthly['cumulative_revenue'].iloc[-1])} "
        "by the end of the selected period."
    )

    heatmap_data = (
        filtered_df.groupby(["Quarter", "Month"], as_index=False)[config.REVENUE_COLUMN]
        .sum()
        .pivot(index="Quarter", columns="Month", values=config.REVENUE_COLUMN)
        .fillna(0)
    )
    fig = px.imshow(
        heatmap_data,
        color_continuous_scale="Teal",
        aspect="auto",
        labels=dict(color="Revenue"),
    )
    fig.update_traces(hovertemplate="Quarter: %{y}<br>Month: %{x}<br>Revenue: $%{z:,.2f}<extra></extra>")
    render_chart(apply_chart_theme(fig, "Revenue Heatmap: Month vs Quarter"))
    render_insight("The heatmap highlights where revenue concentration is strongest across month-quarter combinations.")

    render_executive_insights(
        [
            trend_phrase(kpis["monthly_growth_pct"], "Latest monthly revenue"),
            trend_phrase(kpis["revenue_growth_pct"], "Revenue from first to latest selected month"),
            f"Average order value is {format_currency(kpis['average_order_value'])} across {format_metric(kpis['total_transactions'])} transactions.",
        ]
    )
    render_footer(last_refresh)


main()
